Ability_list:
  - 'Install the water pump'
  - 'Connect the water pump to the drainage pipe'
  - 'Lifting objects such as piles and pumps'

knowledge_of_decomposition : |
    All tasks to be published should adhere to the following JSON format:
    '''json
    {
    "Task type": string // The type of task to be published. This type should be chosen from one of the following: preliminary task, collaborative task, subsequent task, independent task, or incremental task.
    "Content": string // The specific content of the task to be published.
    "Priority": int // if (the type of task to be published is a preliminary task) then [fill in %d], 
    elseif (the type of task to be published is a collaborative task, independent task, or incremental task) then [fill in %d], 
    elseif (the type of task to be published is a subsequent task) then [fill in %d].
    }'''
    """ % (overall_task_dict["Priority"] + 1, overall_task_dict["Priority"], overall_task_dict["Priority"] - 1)

Install_the_water_pump:
  content: 'Install the water pump'
  efficiency: 0.4
  knowledge_template: |
    if (there is no passable path from the point {Current location of the robot} to the point {Installation location of the water pump})
    then [
      if ({Ground state} == hard)
        then [publish preliminary task: Clear a passable path from point {Current location of the robot} to the point {Installation location of the water pump}.]
      elseif ({Ground state} == soft)
        then [publish preliminary task: Lay down a working path to create a specialized working path from point {Current location of the robot} to the point {Installation location of the water pump}.]
    ]
    if (the water pump is not at point {Installation location of the water pump})
    then [
      publish preliminary task: Transport the water pump from point {Current location of the water pump} to the point {Installation location of the water pump}.
    ]
  knowledge_needed_input: |
    '''json
    {
      "Installation location of the water pump": string // Please fill in the coordinates or representative letter of the water pump installation location. If neither is explicitly specified, this item should be filled in as unknown.
      "Current location of the water pump": string // Please fill in the current coordinates or representative letter of the water pump. If neither is explicitly specified, this item should be filled in as unknown.
      "Current location of the robot": string // Please fill in the coordinates or representative letter of the robot's current location. If neither is explicitly specified, this item should be filled in as unknown.
      "Ground state": string // If the ground is soft, fill in soft. If the ground is hard, fill in hard. If neither is explicitly specified, this item should be filled in as unknown.
    }'''
  function:
    - 'go_to({nav_goal})'
    - 'install()'
  function_needed_input_list:
    - 'nav_goal'

Connect_the_water_pump_to_the_drainage_pipe:
  content: 'Connect the water pump to the drainage pipe'
  efficiency: 0.4
  knowledge: |
    if (the water pump is not connected to the drainage pipe)
    then [
      publish preliminary task: Transport the water pump from point {Current location of the water pump} to the point {Drainage pipe installation location}.
    ]
  knowledge_needed_input: |
    '''json
    {
      "Current location of the water pump": string // Please fill in the coordinates or representative letter of the water pump's current location. If neither is explicitly specified, this item should be filled in as unknown.
      "Drainage pipe installation location": string // Please fill in the coordinates or representative letter of the drainage pipe installation location. If neither is explicitly specified, this item should be filled in as unknown.
    }'''
  function:
    - 'go_to({nav_goal})'
    - 'connect()'
  function_needed_input_list:
    - 'nav_goal'

Lifting_objects_such_as_piles_and_pumps:
  content: 'Lifting objects such as piles and pumps'
  efficiency: 0.3
  knowledge: |
    if (there is no passable path from the point {Current location of the robot} to the point {Installation location of the water pump})
    then [
      if ({Ground state} == hard)
        then [publish preliminary task: Clear a passable path from point {Current location of the robot} to the point {Installation location of the water pump}.]
      elseif ({Ground state} == soft)
        then [publish preliminary task: Lay down a working path to create a specialized working path from point {Current location of the robot} to the point {Installation location of the water pump}.]
    ]
    if (the water pump is not at point {Installation location of the water pump})
    then [
      publish preliminary task: Transport the water pump from point {Current location of the water pump} to the point {Installation location of the water pump}.
    ]
  knowledge_needed_input: |
    '''json
    {
      "Installation location of the water pump": string // Please fill in the coordinates or representative letter of the water pump installation location. If neither is explicitly specified, this item should be filled in as unknown.
      "Current location of the water pump": string // Please fill in the current coordinates or representative letter of the water pump. If neither is explicitly specified, this item should be filled in as unknown.
      "Current location of the robot": string // Please fill in the coordinates or representative letter of the robot's current location. If neither is explicitly specified, this item should be filled in as unknown.
      "Ground state": string // If the ground is soft, fill in soft. If the ground is hard, fill in hard. If neither is explicitly specified, this item should be filled in as unknown.
    }'''
  function:
    - 'go_to({nav_goal})'
    - 'install()'
  function_needed_input_list:
    - 'nav_goal'